README.md
drivers/common/ionic_if.h
drivers/linux/Makefile
drivers/linux/eth/ionic/Makefile
drivers/linux/eth/ionic/ionic.h
drivers/linux/eth/ionic/ionic_dev.c
drivers/linux/eth/ionic/ionic_dev.h
drivers/linux/eth/ionic/ionic_devlink.c
drivers/linux/eth/ionic/ionic_ethtool.c
drivers/linux/eth/ionic/ionic_fw.c
drivers/linux/eth/ionic/ionic_lif.c
drivers/linux/eth/ionic/ionic_lif.h
drivers/linux/eth/ionic/ionic_main.c
drivers/linux/eth/ionic/ionic_rx_filter.c
drivers/linux/eth/ionic/ionic_stats.c
drivers/linux/eth/ionic/ionic_txrx.c
drivers/linux/eth/ionic/kcompat.h
drivers/linux/mnet/mnet_drv.c
drivers/linux/mnet/mnet_drv.h

- FW update fixes
- Makefile cleanups
- Add support for choosing individual Tx and Rx interrupts rather than paired
- Fix memory leaks and timing issues
- Kcompat fixes for newer upstream and Red Hat kernels
- Add interrupt affinity option for mnic_ionic use
- Other optimizations and stability fixes

drivers: update code to match 1.15.3-C-14

---

README.md
drivers/common/ionic_if.h
drivers/linux/Makefile
drivers/linux/eth/ionic/Makefile
drivers/linux/eth/ionic/ionic.h
drivers/linux/eth/ionic/ionic_api.c
drivers/linux/eth/ionic/ionic_api.h
drivers/linux/eth/ionic/ionic_bus_pci.c
drivers/linux/eth/ionic/ionic_bus_platform.c
drivers/linux/eth/ionic/ionic_debugfs.c
drivers/linux/eth/ionic/ionic_debugfs.h
drivers/linux/eth/ionic/ionic_dev.c
drivers/linux/eth/ionic/ionic_dev.h
drivers/linux/eth/ionic/ionic_devlink.c
drivers/linux/eth/ionic/ionic_devlink.h
drivers/linux/eth/ionic/ionic_ethtool.c
drivers/linux/eth/ionic/ionic_fw.c
drivers/linux/eth/ionic/ionic_lif.c
drivers/linux/eth/ionic/ionic_lif.h
drivers/linux/eth/ionic/ionic_main.c
drivers/linux/eth/ionic/ionic_rx_filter.c
drivers/linux/eth/ionic/ionic_rx_filter.h
drivers/linux/eth/ionic/ionic_stats.c
drivers/linux/eth/ionic/ionic_stats.h
drivers/linux/eth/ionic/ionic_txrx.c
drivers/linux/eth/ionic/ionic_txrx.h
drivers/linux/eth/ionic/kcompat.h
drivers/linux/linux_ver.mk
drivers/linux/mnet/mnet_drv.c
drivers/linux/mnet/mnet_drv.h

- Added support for PTP
- Dropped support for macvlan offload
- Cleaned some 'sparse' complaints
- Add support for devlink firmware update
- Dynamic interrupt coalescing
- Add support for separate Tx interrupts
- Rework queue reconfiguration for better memory handling
- Reorder some configuration steps to remove race conditions
- Changes to napi handling for better performance

drivers: driver updates to 1.15.4-C-8

---

README.md
drivers/linux/Makefile
drivers/linux/eth/ionic/Makefile
drivers/linux/eth/ionic/ionic_bus_platform.c
drivers/linux/eth/ionic/ionic_dev.c
drivers/linux/eth/ionic/ionic_devlink.c
drivers/linux/eth/ionic/ionic_devlink.h
drivers/linux/eth/ionic/ionic_ethtool.c
drivers/linux/eth/ionic/ionic_fw.c
drivers/linux/eth/ionic/ionic_lif.c
drivers/linux/eth/ionic/ionic_main.c
drivers/linux/eth/ionic/ionic_phc.c
drivers/linux/eth/ionic/ionic_phc_weak.c
drivers/linux/eth/ionic/ionic_stats.c
drivers/linux/eth/ionic/kcompat.h
drivers/linux/mnet/mnet_drv.c

driver updates include:
- weak links for PTP api for compile and load on DSC kernel without PTP support
- don't set up PTP in ionic_mnic if PTP bar is not available
- close a small window to prevent starting queues when in FW reset
- other small bug fixes to PTP support
- compat fixes for compiling on Linux v5.11
- guard against adminq use after free

drivers: update driver code to 1.15.5-C-4

---

README.md
drivers/linux/mdev/Makefile

The Makefile got lost in the driver name change, so add it
back into the release.  Also updating the example make lines
in the README.

drivers: add new Makefile for mdev

---

README.md
drivers/common/ionic_if.h
drivers/linux/Makefile
drivers/linux/eth/ionic/ionic.h
drivers/linux/eth/ionic/ionic_api.c
drivers/linux/eth/ionic/ionic_debugfs.c
drivers/linux/eth/ionic/ionic_dev.c
drivers/linux/eth/ionic/ionic_dev.h
drivers/linux/eth/ionic/ionic_ethtool.c
drivers/linux/eth/ionic/ionic_lif.c
drivers/linux/eth/ionic/ionic_lif.h
drivers/linux/eth/ionic/ionic_txrx.c
drivers/linux/eth/ionic/kcompat.c
drivers/linux/eth/ionic/kcompat.h

- added support for cmb-rings
CMB = Controller Memory Buffers
- rx_mode locking to block thread race
- struct ionic_lif rework for better cache line layout

drivers: updates for 1.15.8.12

---

README.md
drivers/common/ionic_if.h
drivers/linux/Makefile
drivers/linux/eth/ionic/ionic_bus_pci.c
drivers/linux/eth/ionic/ionic_dev.c
drivers/linux/eth/ionic/ionic_dev.h
drivers/linux/eth/ionic/ionic_lif.c
drivers/linux/eth/ionic/ionic_lif.h
drivers/linux/eth/ionic/ionic_phc.c
drivers/linux/eth/ionic/ionic_txrx.c
drivers/linux/eth/ionic/kcompat.h

- monitoring fw status generation for fw restart hints
- catch lack of PTP support earlier in service routine
- makefile fixes for sles 15 sp3
- lower page splitting limit to better account for headers
- VF stats area fix for PF
- better thread-safe rx_mode work

drivers: updates for 1.15.9.7

---

README.md
drivers/linux/Makefile
drivers/linux/eth/ionic/ionic_bus_platform.c
drivers/linux/eth/ionic/ionic_dev.c
drivers/linux/eth/ionic/ionic_dev.h
drivers/linux/eth/ionic/ionic_ethtool.c
drivers/linux/eth/ionic/ionic_lif.c
drivers/linux/eth/ionic/ionic_lif.h
drivers/linux/eth/ionic/ionic_main.c
drivers/linux/eth/ionic/ionic_rx_filter.c
drivers/linux/eth/ionic/ionic_rx_filter.h
drivers/linux/eth/ionic/ionic_txrx.c

- Added watchdog to platform for closer tracking of FW updates
and crash recycle
- Fixed dynamic interrupt management accounting
- Fixes for mac filter management

drivers: updates for 1.15.9.21

---

README.md
drivers/linux/Makefile
drivers/linux/eth/ionic/ionic_lif.c
drivers/linux/eth/ionic/ionic_main.c

- Additional queue config locking for stress timing issue
- Suppressed unnecessary log message

drivers: updates for 1.15.9-C-28

---

README.md
drivers/linux/Makefile
drivers/linux/eth/ionic/kcompat.h

Remove an unnecessary kcompat macro

dsc-drivers: update for 1.15.9-C-64

---

README.md
drivers/common/ionic_regs.h
drivers/linux/Makefile
drivers/linux/eth/ionic/Makefile
drivers/linux/eth/ionic/ionic.h
drivers/linux/eth/ionic/ionic_api.c
drivers/linux/eth/ionic/ionic_bus.h
drivers/linux/eth/ionic/ionic_bus_pci.c
drivers/linux/eth/ionic/ionic_bus_platform.c
drivers/linux/eth/ionic/ionic_debugfs.c
drivers/linux/eth/ionic/ionic_dev.c
drivers/linux/eth/ionic/ionic_dev.h
drivers/linux/eth/ionic/ionic_devlink.c
drivers/linux/eth/ionic/ionic_ethtool.c
drivers/linux/eth/ionic/ionic_lif.c
drivers/linux/eth/ionic/ionic_lif.h
drivers/linux/eth/ionic/ionic_main.c
drivers/linux/eth/ionic/ionic_phc.c
drivers/linux/eth/ionic/ionic_rx_filter.c
drivers/linux/eth/ionic/ionic_rx_filter.h
drivers/linux/eth/ionic/ionic_stats.c
drivers/linux/eth/ionic/ionic_stats.h
drivers/linux/eth/ionic/ionic_txrx.c
drivers/linux/eth/ionic/kcompat.h

Overview:
- add vlan filter management to mac filter management
- update filter management for handling overflow
- updates for recent upstream kernels and distros
- better handling of various FW recovery scenarios
- equivalent to linux-ionic 22.01.1-003
Detailed internal patch list:
ionic: add queue lock around open and stop
ionic: catch up to changes from upstream mac filter updates
ionic: refactor ionic_lif_addr to remove a layer
ionic: handle mac filter overflow
ionic: fix type conversion
ionic: rearrange hwstamp use of queue_lock
ionic: squelch the right message
ionic: fix up kcompat for ndo_eth_ioctl
ionic: fix double use of queue-lock
ionic: fix wording of CMB no support message
ionic: fix up devlink api for linux 5.15 changes
ionic: fix up get/set_coalesce kcompat for 5.15
ionic: …

dsc-drivers: update drivers for 1.15.9-C-65

---

README.md
drivers/linux/Makefile
drivers/linux/eth/ionic/ionic.h
drivers/linux/eth/ionic/ionic_api.c
drivers/linux/eth/ionic/ionic_api.h
drivers/linux/eth/ionic/ionic_bus.h
drivers/linux/eth/ionic/ionic_bus_pci.c
drivers/linux/eth/ionic/ionic_bus_platform.c
drivers/linux/eth/ionic/ionic_debugfs.c
drivers/linux/eth/ionic/ionic_debugfs.h
drivers/linux/eth/ionic/ionic_dev.c
drivers/linux/eth/ionic/ionic_dev.h
drivers/linux/eth/ionic/ionic_devlink.c
drivers/linux/eth/ionic/ionic_devlink.h
drivers/linux/eth/ionic/ionic_ethtool.c
drivers/linux/eth/ionic/ionic_ethtool.h
drivers/linux/eth/ionic/ionic_fw.c
drivers/linux/eth/ionic/ionic_lif.c
drivers/linux/eth/ionic/ionic_lif.h
drivers/linux/eth/ionic/ionic_main.c
drivers/linux/eth/ionic/ionic_phc.c
drivers/linux/eth/ionic/ionic_phc_weak.c
drivers/linux/eth/ionic/ionic_rx_filter.c
drivers/linux/eth/ionic/ionic_rx_filter.h
drivers/linux/eth/ionic/ionic_stats.c
drivers/linux/eth/ionic/ionic_stats.h
drivers/linux/eth/ionic/ionic_txrx.c
drivers/linux/eth/ionic/ionic_txrx.h
drivers/linux/eth/ionic/kcompat.h
drivers/linux/mdev/mdev_drv.c

Overview:
update to match linux drivers 22.05.1-001
Detailed internal patch list:
ionic: fix type complaint in ionic_dev_cmd_clean()
ionic: Add debugfs support to count number of Tx/Rx allocations
ionic: Use vzalloc for large per-queue related buffers
ionic: Fix memory leak during surprise FW reset
ionic: update copyright strings
ionic: general code fixups
mdev: quiet a needless irq complaint
ionic: catch transition back to RUNNING with fw_generation 0
ionic: kcompat for v5.17, RHEL 9.0, RHEL 8.6
mdev: ignore request to start existing device
ionic: clear broken state on generation change

dsc-drivers: update drivers for 1.15.9-C-100

---

README.md
drivers/common/ionic_if.h
drivers/linux/Makefile
drivers/linux/eth/ionic/Makefile
drivers/linux/eth/ionic/ionic.h
drivers/linux/eth/ionic/ionic_bus_pci.c
drivers/linux/eth/ionic/ionic_debugfs.c
drivers/linux/eth/ionic/ionic_dev.c
drivers/linux/eth/ionic/ionic_dev.h
drivers/linux/eth/ionic/ionic_ethtool.c
drivers/linux/eth/ionic/ionic_ethtool.h
drivers/linux/eth/ionic/ionic_lif.c
drivers/linux/eth/ionic/ionic_lif.h
drivers/linux/eth/ionic/ionic_main.c
drivers/linux/eth/ionic/ionic_phc_weak.c
drivers/linux/eth/ionic/ionic_stats.c
drivers/linux/eth/ionic/ionic_txrx.c
drivers/linux/eth/ionic/kcompat.h

Update the dsc-drivers to match internal 22.11.1-001 drivers
ionic: VF ethernet interfaces come up with out MAC addresses
ionic: fix up issues with handling EAGAIN on FW cmds
ionic: fix vlan feature check
ionic: eliminate temporary descriptor used for tx posting
ionic: replay VF attributes after fw crash recovery
ionic: enable tunnel offloads
ionic: make rx fill threshold configurable
ionic: tag all cmb ring & descriptor pointers with __iomem cookie
ionic: new ionic device identity level and VF start control
ionic: only save the user set VF attributes
ionic: page cache for rx buffers
ionic: Fix crash when reconfiguring queues multiple times
ionic: memset fix for vf attr replay
ionic: compat for new netif_napi_add() parameters in v6.1
ionic: change order of devlink …

dsc-drivers: update ionic drivers to 22.11.1-001

---

drivers/linux/pciesvc/README.md
drivers/linux/pciesvc/pciesvc/include/virtio_spec.h
drivers/linux/pciesvc/pciesvc/src/cfg.c
drivers/linux/pciesvc/pciesvc/src/virtio.c

Overview
virtio register improvements for features, status
preserve MaxPayload setting across FLR resets
- vdpa: fix up use of virtio BAR config for device_status and virtio_net_config
- virtio: Fixes around features and status bits
- pciesvc: preserve MaxPayload setting across FLR resets

Update to 1.59.0-C-5

---

drivers/linux/pciesvc/README.md
drivers/linux/pciesvc/pciesvc/include/pcieshmem.h
drivers/linux/pciesvc/pciesvc/include/pciesvc.h
drivers/linux/pciesvc/pciesvc/include/virtio_spec.h
drivers/linux/pciesvc/pciesvc/src/bar.c
drivers/linux/pciesvc/pciesvc/src/cfg.c
drivers/linux/pciesvc/pciesvc/src/pciesvc_impl.h
drivers/linux/pciesvc/pciesvc/src/pmt.c
drivers/linux/pciesvc/pciesvc/src/prt.c
drivers/linux/pciesvc/pciesvc/src/virtio.c

Overview
Improved error handling during resource allocation. Virtio enhancements, preliminary legacy device support. Bump pciesvc version to 3.2 (was 3.1).
- Handle the device, PMT and PRT alloc error in finalize (#61332)
- virtio: Updates for PCI, OPROM, CVQ, crash recovery (#62484)
- virtio: CVQ queue id, crash recovery support (#63210)
- pciemgrd: virtio sriov scale (#63779)
- pciemgrd: fix pmt leak in pmt_free (#63911)
- virtio: Logging levels, edmaq return codes (#64053)
- virtio: Partial legacy device support (#64431)
- Salina athena (#64820)
- Eth and Virtio devices recovery support, istate implementation (#64739)
- virtio: move cvq crash recovery data from common regs to istate (#65304)
- pciesvc: version to 3.2 (#66013)

Update pciesvc to 1.63.0-C-8

---

drivers/linux/pciesvc/pciesvc/include/pciesvc.h
drivers/linux/pciesvc/pciesvc/include/virtio_spec.h
drivers/linux/pciesvc/pciesvc/src/virtio.c

Overview:
Virtio/vpda improvements, support split vqs.
Bump pciesvc version to 3.3
* pciesvc: virtio MTU depending on VIRTIO_NET_F_MRG_RXBUF (#65401)
* pciesvc: version to 3.3 (#66014)
* virtio: Init work around features bitmask (#65903)
* virtio: split vq initial changes (#65891)
* vdpa: live migration work for set_vq_state (#66440)
* virtio: Fixes for split VQs (#67515)

pciesvc: update to 1.65-C-6

---

drivers/linux/pciesvc/pciesvc/include/pciesvc.h
drivers/linux/pciesvc/pciesvc/include/virtio_spec.h
drivers/linux/pciesvc/pciesvc/src/virtio.c

Overview:
Virtio/vpda improvements, support split vqs.
Bump pciesvc version to 3.3
* pciesvc: virtio MTU depending on VIRTIO_NET_F_MRG_RXBUF (#65401)
* pciesvc: version to 3.3 (#66014)
* virtio: Init work around features bitmask (#65903)
* virtio: split vq initial changes (#65891)
* vdpa: live migration work for set_vq_state (#66440)
* virtio: Fixes for split VQs (#67515)

pciesvc: update to 1.65-C-6 (#31)

---

README.md
drivers/common/ionic_if.h
drivers/linux/Makefile
drivers/linux/eth/ionic/ionic_bus.h
drivers/linux/eth/ionic/ionic_bus_pci.c
drivers/linux/eth/ionic/ionic_bus_platform.c
drivers/linux/eth/ionic/ionic_debugfs.c
drivers/linux/eth/ionic/ionic_dev.h
drivers/linux/eth/ionic/ionic_ethtool.c
drivers/linux/eth/ionic/ionic_lif.c
drivers/linux/eth/ionic/ionic_lif.h
drivers/linux/eth/ionic/ionic_txrx.c
drivers/linux/eth/ionic/kcompat.h
drivers/linux/linux_ver.mk

Update the ionic drivers to match version 23.07.1-001 
ionic: remove noise from ethtool rxnfc error msg
linux-ionic: Fix multiple defined issue on oot driver
ionic: add support for ethtool extended stat link_down_count
ionic: update link down count to exclude VF link state down
ionic: Add debugfs entry for dim coalesce value in usecs
ionic: Use a custom dim profile
ionic: page reuse seems to be causing use-after-free on ARM.
ionic: extract common bits from probe and remove
ionic: pull out common bits from fw_up
ionic: add FLR recovery support
ionic: kcompat for RHEL 8.8
ionic: remove WARN_ON
ionic: Add script to install driver from source

dsc-drivers: update ionic drivers to 23.07.1-001

---

README.md
drivers/linux/Makefile
drivers/linux/eth/ionic/ionic_bus_pci.c
drivers/linux/eth/ionic/ionic_dev.c
drivers/linux/eth/ionic/ionic_dev.h
drivers/linux/eth/ionic/ionic_ethtool.c
drivers/linux/eth/ionic/ionic_lif.c
drivers/linux/eth/ionic/ionic_txrx.c

Update the drivers to match 23.08.1-001
ionic: update FLR handling from upstream comments
ionic: other upstream diffs to catch up to
ionic: fix up initial coalesce_usec values
ionic: more FLR catchup from upstream comments
ionic: count SGs in packet to minimize linearize
ionic: add a check for max SGs and SKB frags
ionic: expand the descriptor bufs array
ionic: Add function ionic_check_valid_mtu
ionic: Add missing err handling for ionic_start_queues_reconfig
Revert "ionic: page reuse seems to be causing use-after-free on ARM."

dsc-drivers: update ionic drivers to 23.08.1-001

---

drivers/linux/pciesvc/Makefile
drivers/linux/pciesvc/README.md
drivers/linux/pciesvc/kpci_test.c
drivers/linux/pciesvc/kpcimgr_module.c
drivers/linux/pciesvc/pciesvc/include/pciehw.h
drivers/linux/pciesvc/pciesvc/include/pciehwmem.h
drivers/linux/pciesvc/pciesvc/include/pcieshmem.h
drivers/linux/pciesvc/pciesvc/include/pciesvc.h
drivers/linux/pciesvc/pciesvc/src/cfg.c
drivers/linux/pciesvc/pciesvc/src/pciesvc_impl.h
drivers/linux/pciesvc/pciesvc/src/pmt.c
drivers/linux/pciesvc/pciesvc/src/prt.c
drivers/linux/pciesvc/pciesvc/src/serial.c

Overview:
Increase scale to 2k vfs.
Add modinfo version=3.5, intree=Y.
Replace gcc-generated reference to memcpy to explicit pciesvc_memcpy. Makefile in module src bundle builds both pciesvc.ko,pciesvc_upg.ko. Bump pciesvc version to 3.5
- Pciemgrd: Scale number of devices to 2048 (#69602)
- pciesvc.ko: add module info version, intree=Y (#71131)
- pciesvc: spmt_dup_prts copy all prts (#71821)
- pciesvc.ko: improve Makefile in module src bundle (#71874)

pciesvc: update to 1.65-C-35

---

README.md
drivers/linux/Makefile
drivers/linux/eth/ionic/ionic_dev.h
drivers/linux/eth/ionic/ionic_lif.c
drivers/linux/eth/ionic/ionic_lif.h
drivers/linux/eth/ionic/ionic_rx_filter.h
drivers/linux/eth/ionic/ionic_txrx.c
drivers/linux/eth/ionic/kcompat.h

ionic: copy the page_cache pointer in queue reconfig
ionic: Make the check for Tx HW timestamping more obvious
ionic: add kcompat for vcalloc
ionic: fix 16bit math issue when PAGE_SIZE >= 64KB
ionic: Remove unused declarations
ionic: use vcalloc rather than vzalloc
out-of-tree: cleanup and fix symvers issues
ionic: Only allocate page-cache for Rx queues
ionic: Don't check null when calling vfree()

dsc-drivers: update ionic drivers to 23.09.1-001

---

README.md
drivers/linux/Makefile
drivers/linux/eth/ionic/Makefile
drivers/linux/eth/ionic/ionic.h
drivers/linux/eth/ionic/ionic_bus_pci.c
drivers/linux/eth/ionic/ionic_debugfs.c
drivers/linux/eth/ionic/ionic_dev.c
drivers/linux/eth/ionic/ionic_dev.h
drivers/linux/eth/ionic/ionic_lif.c
drivers/linux/eth/ionic/ionic_lif.h
drivers/linux/eth/ionic/ionic_main.c
drivers/linux/eth/ionic/ionic_trace.h
drivers/linux/eth/ionic/ionic_txrx.c
drivers/linux/eth/ionic/kcompat.h

ionic: Fix dim work handling in split interrupt mode
ionic: Rename dim profile to be more generic
ionic: remove extra call to ionic_debugfs_add_lif
ionic: fix snprintf format length warning
ionic: remove lifbits and ethbits
ionic: whitespace diffs from upstream
ionic: add ionic_write_cmb_desc to clean up code
ionic: no need for pci reset in recovery
ionic: do full teardown on reset even if fw_down
ionic: fill out pci error handlers
ionic: sync up the napi processing on queue stop

dsc-drivers: update ionic drivers to 23.12.2-001

---

drivers/linux/pciesvc/Makefile
drivers/linux/pciesvc/kpci_constants.h
drivers/linux/pciesvc/kpci_entry.S
drivers/linux/pciesvc/kpci_get_entry.c
drivers/linux/pciesvc/kpci_kexec.c
drivers/linux/pciesvc/kpci_test.c
drivers/linux/pciesvc/kpcimgr_api.h
drivers/linux/pciesvc/kpcimgr_module.c
drivers/linux/pciesvc/kpcinterface.c
drivers/linux/pciesvc/pciesvc_end.c
drivers/linux/pciesvc/pciesvc_loader/Makefile
drivers/linux/pciesvc/pciesvc_loader/pciesvc_loader.c
drivers/linux/pciesvc/pciesvc_system_extern.h
drivers/linux/pciesvc/tools/reloc_check

Overview:
Update module wrapper to support pciesvc_loader and pciesvc.lib. Maintain compatibility with pciesvc.ko module.
pciesvc version unchanged at 3.5
- kpcimgr: pciesvc.lib support
- pcisvc_lib: use TOOLCHAIN_PREFIX for toolchain
- kpcimgr: ksrc packs pciesvc_loader, CC -fno-store-merging support

pciesvc: update to 1.65-C-69 (#41)

---

README.md
drivers/common/ionic_if.h
drivers/linux/Makefile
drivers/linux/eth/ionic/ionic.h
drivers/linux/eth/ionic/ionic_api.c
drivers/linux/eth/ionic/ionic_debugfs.c
drivers/linux/eth/ionic/ionic_dev.c
drivers/linux/eth/ionic/ionic_dev.h
drivers/linux/eth/ionic/ionic_devlink.c
drivers/linux/eth/ionic/ionic_ethtool.c
drivers/linux/eth/ionic/ionic_fw.c
drivers/linux/eth/ionic/ionic_lif.c
drivers/linux/eth/ionic/ionic_lif.h
drivers/linux/eth/ionic/ionic_main.c
drivers/linux/eth/ionic/ionic_stats.c
drivers/linux/eth/ionic/ionic_txrx.c
drivers/linux/eth/ionic/ionic_txrx.h
drivers/linux/eth/ionic/kcompat.h
drivers/linux/mdev/mdev_drv.c

Work has happened in several internal branches at once over the last few months and it has all come together in the most recent driver release.  This update brings our dsc-drivers repo up-to-date with what we've been using internally and what has been accepted upstream for ionic in Linux v6.9.
This update includes patches to:
Add XDP support
Refactor Tx and Rx fast paths for performance
Refactor struct sizes, layout, and usage for memory savings and performance
The internal patch list is rather long and ugly.  Looking at the patch history in the upstream ionic driver will likely give a clearer overview of what all is here.
ionic: Add initial framework for XDP
ionic: xdp MTU and headroom
ionic: Add XDP action offload stats
ionic: Add XDP support for resizing the packet for XDP_PASS
ionic: …

dsc-drivers: update ionic drivers to 24.03.1-002

---

README.md
drivers/linux/Makefile
drivers/linux/eth/ionic/ionic.h
drivers/linux/eth/ionic/ionic_bus.h
drivers/linux/eth/ionic/ionic_bus_pci.c
drivers/linux/eth/ionic/ionic_bus_platform.c
drivers/linux/eth/ionic/ionic_dev.c
drivers/linux/eth/ionic/ionic_dev.h
drivers/linux/eth/ionic/ionic_lif.c
drivers/linux/eth/ionic/ionic_lif.h
drivers/linux/eth/ionic/ionic_main.c
drivers/linux/eth/ionic/ionic_txrx.c

This is a driver update for testing of a different algorithm for handling the missed-doorbell fix in the ionic driver.
A latency test in a scaled out setting (many VMs with many queues) uncovered an issue with our earlier missed doorbell fix.  The basic issue is that we're delaying things with a timer for every single queue periodically using mod_timer() to reset itself, and mod_timer() becomes a more and more expensive thing as there are more and more VFs and queues each with their own timer.  A ping-pong latency test tends to exacerbate the effect such that every napi is doing a mod_timer() in every cycle.
This version replaces all the per-queue timers with a new workqueue per device, using a periodically workitem scheduled on the AdminQ's last cpu which queues a workitem per running …

dsc-drivers: update drivers to 24.04.2-002

---

drivers/linux/Makefile
drivers/linux/eth/ionic/ionic_dev.c
drivers/linux/eth/ionic/ionic_lif.c

Use cancel_delayed_work_sync() on our delayed work items rather than cancel_work_sync() to be sure the timers get cleaned up correctly.
Since the qcq's are down over FW_RESET, don't check them for missed doorbell issues.

ionic: use cancel_delayed_work

---

drivers/common/ionic_if.h
drivers/linux/Makefile
drivers/linux/eth/ionic/dim.c
drivers/linux/eth/ionic/ionic.h
drivers/linux/eth/ionic/ionic_bus_platform.c
drivers/linux/eth/ionic/ionic_debugfs.c
drivers/linux/eth/ionic/ionic_dev.c
drivers/linux/eth/ionic/ionic_dev.h
drivers/linux/eth/ionic/ionic_ethtool.c
drivers/linux/eth/ionic/ionic_lif.c
drivers/linux/eth/ionic/ionic_lif.h
drivers/linux/eth/ionic/ionic_main.c
drivers/linux/eth/ionic/ionic_txrx.c
drivers/linux/eth/ionic/net_dim.c
drivers/linux/mdev/mdev_drv.c

Summary
- rework of platform_device management to better follow kernel device model
- refinements on the missed-doorbell workaround
- whitespace and comment cleanup in ionic_if.h
ionic: simplify alloc_netdev routines ionic: platform code cleanup drivers: complain about early probe no resources drivers: no platform devicetree match mdev: simplify the uio driver naming mdev: simplify resource builder function calls mdev: clean up devicetree node search mdev: rework for dynamic pdev and no direct probe ionic: no export of probe and remove drivers: fix up platform device name Makefile: add kernel ver message drivers: fix up code checker complaints mdev: depend on the is_uio bit for using UIO driver mdev: remove devices on rmmod ionic: correct use of platform_data ionic: …

dsc-drivers: update to 24.05.1-001

---

README.md
drivers/linux/Makefile
drivers/linux/eth/ionic/Makefile
drivers/linux/eth/ionic/ionic_bus_platform.c
drivers/linux/eth/ionic/ionic_dev.h
drivers/linux/eth/ionic/ionic_if.h
drivers/linux/eth/ionic/ionic_lif.c
drivers/linux/eth/ionic/kcompat.h
drivers/linux/mdev/mdev_drv.c

Small updates
ionic: Prevent tx_timeout due to frequent doorbell ringing
ionic_mnic: fix up ptp connections for newer kernel
ionic_mnic: fix up msi search for newer kernel
mdev: fix up for building with buildroot_2024
build: fix Makefile for buildroot_2024
ionic: Store int_mnic ip in dev info region of host mgmt

dsc-drivers: update to 24.07.1-001

---

README.md
drivers/linux/Makefile
drivers/linux/etc/Makefile.common
drivers/linux/etc/kernel_compat_funcs.sh
drivers/linux/eth/ionic/Makefile
drivers/linux/eth/ionic/ionic.h
drivers/linux/eth/ionic/ionic_api.c
drivers/linux/eth/ionic/ionic_api.h
drivers/linux/eth/ionic/ionic_aux.c
drivers/linux/eth/ionic/ionic_aux.h
drivers/linux/eth/ionic/ionic_bus_pci.c
drivers/linux/eth/ionic/ionic_bus_platform.c
drivers/linux/eth/ionic/ionic_debugfs.c
drivers/linux/eth/ionic/ionic_dev.c
drivers/linux/eth/ionic/ionic_dev.h
drivers/linux/eth/ionic/ionic_devlink.c
drivers/linux/eth/ionic/ionic_devlink.h
drivers/linux/eth/ionic/ionic_ethtool.c
drivers/linux/eth/ionic/ionic_fw.c
drivers/linux/eth/ionic/ionic_if.h
drivers/linux/eth/ionic/ionic_lif.c
drivers/linux/eth/ionic/ionic_lif.h
drivers/linux/eth/ionic/ionic_main.c
drivers/linux/eth/ionic/ionic_phc.c
drivers/linux/eth/ionic/ionic_sysfs.c
drivers/linux/eth/ionic/ionic_sysfs.h
drivers/linux/eth/ionic/ionic_txrx.c
drivers/linux/eth/ionic/kcompat.h
drivers/linux/eth/ionic/kernel_compat.sh

Several updates including:
- support for new Salina device RDMA driver
- new kernel_compat.sh feature for better auto-configure of various distribution kernels
- better ethtool support for 50, 200, and 400 Gbe QSFP modules
ionic: fix debugfs q stats pointer
ionic_rdma: clear CMB requested region in eth driver (AI-367)
ionic: change devlink registration sequence
ionic: rework compat handling of devlink param ENABLE_RDMA
ionic_rdma: queue group oriented dual-udma
ionic: MOFED aux device compatibility
ionic: updates for Linux kernel v6.13
ionic: set pci max seg size to 1G.
ionic: use ee->offset when returning sprom data
ionic: add new qsfp type support
ionic: remove unsupported rx rule related code
ionic: kcompat tweaks for RHEL 9.5
ionic: Fix the ethtool outputs issues …

dsc-drivers: update ionic to 25.01.1-001

---

bin/prep-kernel-layout.sh

Add a script that copies the driver sources into a directory structure that could be overlaid onto the Linux kernel source tree.  Some file tweaking is done to try to match the paths where needed.

tools: script for Linux kernel layout
